# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---


Exercise 1:

Create a NumPy array of integers from 1 to 10.

# Exercise 1

In [1]:
import numpy as np

In [32]:
my_integers = np.arange(1, 11)
my_integers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Exercise 2:

Create a 3x3 NumPy array filled with zeros.

# Exercise 2

In [10]:
my_zero = np.zeros((3,3))
my_zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Exercise 3:

Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

# Exercise 3

In [12]:
my_numbers = np.linspace(0, 5, 10)
my_numbers

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Exercise 4:

Create a 5x5 identity matrix using NumPy.

# Exercise 4

In [17]:
my_identity_mat = np.eye(5, 5)
my_identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Exercise 5:

Create a 4x4 matrix with random values between 0 and 1.

# Exercise 5

In [25]:
np.random.randint(2, size = (4,4))

array([[1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 1, 0]])

In [26]:
#help(np.random.randint)

Exercise 6:

Find the shape of a NumPy array.

# Exercise 6



In [33]:
#recall my_integers array

my_integers.shape #a one dimensional array with 10 elements.

(10,)

Exercise 7:

Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

# Exercise 7

In [35]:
np.arange(16).reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Exercise 8:

Find the data type of the elements in a NumPy array.

# Exercise 8

In [39]:
my_integers.dtype

dtype('int64')

Exercise 9:

Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

# Exercise 9



In [44]:
my_int = np.arange(1, 101)
#my_int
my_int[my_int%2 == 0] #indexing

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Exercise 10:

Generate a 6x6 matrix of random integers between 10 and 50.

# Exercise 10

In [45]:
np.random.randint(50, size = (6, 6))

array([[ 1,  3, 40,  9, 35, 44],
       [30, 33,  2,  6, 25, 17],
       [44, 27, 14, 47, 38, 34],
       [47, 43, 32, 30, 12, 15],
       [ 6,  3,  8, 27, 47, 41],
       [16,  1, 41, 13, 49, 21]])

Exercise 11:

Slice a 2D NumPy array to extract a submatrix.

# Exercise 11

In [51]:
my_2darray = np.array([[2, 4, 5, 6], [3, 5, 6, 8]])
print(my_2darray)
my_2darray.shape #checking or confirming it's a 2d array

[[2 4 5 6]
 [3 5 6 8]]


(2, 4)

Exercise 12:

Calculate the sum of all elements in a NumPy array.

# Exercise 12

In [52]:
np.sum(my_2darray) #sum

39

Exercise 13:

Calculate the mean, median, and standard deviation of a NumPy array.

# Exercise 13

In [58]:
print(np.mean(my_2darray))  #mean for the whole array

print(np.median(my_2darray)) #median for the whole array

print(np.std(my_2darray)) #standard deviation for the whole array





4.875
5.0
1.7633419974582356


In [67]:
print(np.mean(my_2darray[0:2, :])) #row 0 and 1 for all column

print(np.mean(my_2darray[:, 0:2])) #all column for row 0 and 2

4.875
3.5


In [56]:
#dir(np)

Exercise 14:

Find the maximum and minimum values in a NumPy array.

# Exercise 14

In [74]:
print(np.max(my_2darray)) #maximum in the array

print(np.min(my_2darray)) #minimum in the array


print(np.max(my_2darray, axis = 0)) #the max in all row, column 0

print(my_2darray)

8
2
[3 5 6 8]
[[2 4 5 6]
 [3 5 6 8]]


In [83]:
my_num2 = np.random.randint(1, 100, size = (5, 8))
my_num2

array([[95, 66, 26, 91, 79, 39, 92, 88],
       [16, 75, 57, 33, 57, 61, 48, 21],
       [19, 45, 16, 61, 41, 99,  2, 60],
       [53, 10, 86, 80, 75, 25, 63, 11],
       [89, 12, 13, 93, 67, 94, 26, 35]])

In [87]:
np.min(my_num2, axis = 0) #column is axis zero while row is 1


array([16, 10, 13, 33, 41, 25,  2, 11])

In [82]:
np.median(my_num2, axis = 1)

array([59.5, 50.5, 27. , 70. , 46. ])

Exercise 15:

Create a NumPy array of 20 random integers and find the index of the maximum value.

# Exercise 15

In [120]:
my_num = np.random.randint(1, 20, size = 20)
print(my_num)
np.argmax(my_num) #index of the maximum number


[15  6 16 10  3  4  9  3  2 13  3 17 16  9  9 15  6  1 16  2]


11

Exercise 16:

Create a NumPy array and reverse its elements.

# Exercise 16

In [122]:
my_num = np.random.randint(1, 20, size = 5)
print(my_num)
np.flip(my_num) #to reverse elements in an array

[ 1  8 16 19 15]


array([15, 19, 16,  8,  1])

Exercise 17:

Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

# Exercise 17

In [132]:
A = np.random.randint(1, 100, size = (3, 3))
print(A)

[[77 44 28]
 [38 67 63]
 [19 13 24]]


In [133]:
B = np.random.randint(50, 100, size = (3, 3))
print(B)

[[99 83 68]
 [95 88 90]
 [75 81 92]]


In [134]:
np.multiply(A, B)

array([[7623, 3652, 1904],
       [3610, 5896, 5670],
       [1425, 1053, 2208]])

Exercise 18:

Create a diagonal matrix from a given 1D array.

# Exercise 18

In [130]:
my_1d_array = np.array([1, 2, 3])
my_1d_array

array([1, 2, 3])

In [131]:
np.diag(my_1d_array) #to create a diagonal matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

Exercise 19:

Perform matrix multiplication on two 2D NumPy arrays.

# Exercise 19

In [145]:
C = np.random.randint(1, 15, size = (2, 2))
C

array([[ 6, 13],
       [ 2,  4]])

In [146]:
D = np.random.randint(5, 10, size = (2, 2))
D

array([[6, 9],
       [5, 7]])

In [147]:
#help(np.matmul) does the matrix multiplication

In [144]:
np.matmul(C, D)

array([[ 44,  63],
       [174, 243]])

Exercise 20:

Flatten a 2D NumPy array into a 1D array.

# Exercise 20

In [150]:
F = np.random.randint(1, 12, size = (2, 2)) 
np.ravel(F)  #to flatten array, use ravel

array([11,  2,  3,  7])

Exercise 21:

Stack two NumPy arrays vertically.

# Exercise 21

In [153]:
np.vstack((A, B)) #stacking arrays vertically

array([[77, 44, 28],
       [38, 67, 63],
       [19, 13, 24],
       [99, 83, 68],
       [95, 88, 90],
       [75, 81, 92]])

Exercise 22:

Stack two NumPy arrays horizontally.

# Exercise 22



In [159]:
G = np.hstack((A, B)) #stacking arrays horizontally


array([[77, 44, 28, 99, 83, 68],
       [38, 67, 63, 95, 88, 90],
       [19, 13, 24, 75, 81, 92]])

Exercise 23:

Split a NumPy array into multiple sub-arrays.

# Exercise 23



In [169]:
np.split(A, 1)

[array([[77, 44, 28],
        [38, 67, 63],
        [19, 13, 24]])]

Exercise 24:

Generate a random NumPy array and round each element to two decimal places.

# Exercise 24

In [176]:
my_float = np.linspace(0, 1, 20)
print(my_float)

np.round(my_float, 2)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


array([0.  , 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53,
       0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.  ])

Exercise 25:

Find the unique elements of a NumPy array.

# Exercise 25

In [186]:
my_num5 = np.random.randint(1, 23, size = 10)
my_num5

array([12, 15,  9, 11, 16, 19, 11, 11,  9, 16])

In [187]:
np.unique(my_num5)

array([ 9, 11, 12, 15, 16, 19])

Exercise 26:

Replace all elements in a NumPy array that are less than a specific value with that value.

# Exercise 26

In [190]:
my_num3 = np.arange(1, 10)

my_num3[my_num3<5] = 6

my_num3

array([6, 6, 6, 6, 5, 6, 7, 8, 9])

Exercise 27:

Find the cumulative sum of the elements in a NumPy array.

# Exercise 27

In [197]:
my_num_7 = np.arange(20)

np.cumsum(my_num_7) #cumulative sum

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190])

Exercise 28:

Create a NumPy array and find the number of non-zero elements in it.

# Exercise 28



In [206]:
s = np.arange(10)
(s[s>0])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Exercise 29:

Create a NumPy array of random integers and sort it in ascending order.

# Exercise 29

In [189]:
my_int5 = np.random.randint(1, 30, size = 20)

my_int5


np.sort(my_int5)

array([ 1,  2,  2,  5,  6,  6,  7,  8,  8,  9, 12, 13, 13, 19, 20, 24, 25,
       27, 28, 28])

Exercise 30:

Find the row-wise and column-wise sum of a 3x3 matrix.

# Exercise 30

In [193]:
my_rad = np.random.randint(1, 100, size = (3, 3))
my_rad

array([[38, 43, 84],
       [61,  7, 93],
       [60, 44, 93]])

In [195]:
np.sum(my_rad, axis = 0) #column-wise

array([159,  94, 270])

In [196]:
np.sum(my_rad, axis = 1) #row-wise

array([165, 161, 197])

Exercise 31:

Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

# Exercise 31

In [261]:
my_n = np.random.randint(1, 30, size = (2, 2))

mean_value = np.mean(my_n)

st_dev = np.std(my_n)


min_n = np.min(my_n)

max_n = np.max(my_n)

normal_dist = (my_n - mean_value)/(max_n - min_n)

normal_dist


array([[-0.58333333,  0.41666667],
       [ 0.41666667, -0.25      ]])

Exercise 32:

Create two NumPy arrays and find the dot product.

# Exercise 32

In [208]:
H = np.random.randint(1, 50, size = (3, 3))

U = np.random.randint(12, 45, size = (3, 3))

np.dot(H, U)

array([[1278, 1031, 1568],
       [3258, 2939, 4534],
       [1920, 1972, 2796]])

Exercise 33:

Find the trace of a square NumPy matrix.

# Exercise 33



In [209]:
np.trace(H)

66

Exercise 34:

Create a 2D array and swap two rows.

# Exercise 34

In [277]:
J = np.random.randint(1, 30, size = (2, 2))

print(J)

J[[0, 1]] = J[[1, 0]]

print(J)

[[16  1]
 [19  4]]
[[19  4]
 [16  1]]


Exercise 35:

Create a 1D NumPy array and convert it into a column vector.

# Exercise 35

In [255]:
my_1d = np.array([1, 2, 5, 6])

col_vec = my_1d[:, None]
col_vec

array([[1],
       [2],
       [5],
       [6]])

Exercise 36:

Find the determinant of a 3x3 matrix.

# Exercise 36



In [234]:
np.random.seed(0)
my_det = np.random.randint(1, 45, size = (3, 3))

np.linalg.det(my_det)



2459.9999999999995

Exercise 37:

Find the eigenvalues and eigenvectors of a 2x2 matrix.

# Exercise 37

In [242]:
from numpy.linalg import eig

my_eig = np.arange(1, 5).reshape(2, 2)
w, v = eig(my_eig)
print(f"Eigen value: {w}")
print(f"Eigen vector: {v}")

Eigen value: [-0.37228132  5.37228132]
Eigen vector: [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Exercise 38:

Solve a system of linear equations using NumPy.

# Exercise 38


In [260]:
k = np.array([[1, 2], [3, 5]])
l = np.array([1, 2])

np.linalg.solve(k, l)

array([-1.,  1.])

Exercise 39:

Add Gaussian noise to a NumPy array.

# Exercise 39

In [267]:
my_arr9 = np.linspace(1, 3, 10)

my_arr9

noise = np.random.normal(0, 2, len(my_arr9)) #the argument are mean, std and size

noise

Gauss_numpy_arr = my_arr9 + noise
Gauss_numpy_arr

array([-1.17160119,  2.50169421,  0.67271777,  0.11514196,  3.88031159,
       -1.75529845,  2.83039459,  2.49306488,  2.49882985,  2.61868804])

Exercise 40:

Create a 4x4 matrix and extract the diagonal elements.

# Exercise 40

In [274]:
np.random.seed(0)

my_arrp = np.random.randint(4, 21, size = (4, 4))
print(my_arrp)
np.diag(my_arrp)

[[16 19  4  7]
 [ 7 11 13  8]
 [10 16  5 10]
 [11 18  9 17]]


array([16, 11,  5, 17])